name: CI BUILD for Docker action 

on:
  push:
    branches: main
    paths: [hello-world-docker-action/**]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run my container action
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: '@EricSoder'

      - name: Output the time set in the container
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"
